- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120hrs"
    TRAINER: "Sivakumar"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"
  
  - name: printthe information again
    vars: #task level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"
  
  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"