- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd 